UOP1_Project/Assets/Scripts/CameraManager.cs

This commit adds a variable to CameraManager.cs that will allow the
sensitivity/speed of the player camera to be modified. By default, the
camera sensitivity is now quicker.

Add Camera Sensitivity

---

UOP1_Project/Assets/Prefabs/Input Reader.asset
UOP1_Project/Assets/Prefabs/Input Reader.asset.meta
UOP1_Project/Assets/Prefabs/Pig.prefab
UOP1_Project/Assets/Scenes/CharController.unity
UOP1_Project/Assets/Scripts/InputReader.cs

What:
Turns scene singleton `InputManager` from `Monobehaviour` into `ScriptableObject`
Why:
Referencing **asset singletons** reduces project complexity while **scene singletons** increase it.

InputReader made into ScriptableObject asset

---

README.md

The commit adds a permanent, non-capped invite link directly to the #open-projects channel on the Official Unity Discord server. Users can choose to collaborate here for quick feedback and non-threaded discussion.

Added Discord Link

---

UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs

Issue: https://github.com/UnityTechnologies/open-project-1/issues/111
The source of the exception was the variable _idx_ following the condition index instead of the last index of _resultGroupsList_
This would give errors every time their values differ since it is expected to have less groups than conditions.
To test, reproduce the steps on the issue or add a bigger number of conditions with different operator combinations, specially chaining AND operators together and some OR operators between those chains.

Fixed the StateTransitionSO error when grouping conditions

---

UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/BeginJumpDescent.asset

Issue: https://github.com/UnityTechnologies/open-project-1/issues/115
This PR also depends on this issue being fixed first: https://github.com/UnityTechnologies/open-project-1/issues/111
Fixed by changing the conditions of the transition BeginJumpDescent to check if the character is in the air.
This avoids the state changing to JumpDescent while the character is in the ground.
Test by moving and jumping the character around the scene with the state machine debug function active.
The character should enter in JumpDescent state only when falling from jumping or from walking towards a ledge.

Fixed the character switching to JumpDescent state while walking

---

UOP1_Project/Assets/Scenes/CharController.unity

There was no forum thread for this PR.
This PR updates the scene so that it meets the conventions.
These changes are necessary to keep up with proper conventions.
I selected all the logical section empty game objects and applied the EditorOnly tag to them.

Applied the tag EditorOnly to logical section GameObjects

---

UOP1_Project/Assets/Scenes/LoadingTest/Beach.unity

There was no forum thread for this PR.
This PR updates the scene so that it meets the conventions.
These changes are necessary to keep up with proper conventions.
I selected all the logical section empty game objects and applied the EditorOnly tag to them. I then tested it and everything ran smooth.

Applied the tag EditorOnly to logical section GameObjects in the Beach scene

---

UOP1_Project/Assets/Scenes/LoadingTest/Forest.unity

There was no forum thread for this PR.
This PR updates the scene so that it meets the conventions.
These changes are necessary to keep up with proper conventions.
I selected all the logical section empty game objects and applied the EditorOnly tag to them. I then tested it and everything ran smooth.

Applied the tag EditorOnly to logical section GameObjects in the Forest scene

---

UOP1_Project/Assets/Shaders/CustomHLSL/CustomLighting.hlsl

Link: #108
There was missing `#else` condition
Now there are no black textures after light baking (look at reproducing issue section)

Fix baked geometry becomes black when no dynamic geometry is on screen

---

UOP1_Project/Assets/Scripts/SpawnSystem.cs

Issue #120 
When the scenes are additively loaded, GameObject instantiation should be put in Start(), because Awake() is exectuted before the new scene becomes active.
Reference thread: https://forum.unity.com/threads/additive-scene-loading-and-awake.660379/

Changed Awake() to Start() in SpawnSystem (#120)

---

UOP1_Project/Assets/ScriptableObjects/Protagonist/States/Idle.asset

Issue: https://github.com/UnityTechnologies/open-project-1/issues/123
Changed the Idle state to support the transition to StartSliding and BeginJumpDescent.
This doubles as a fix and to support any future plans for moving or disappearing objects in the environment that the character can step on.
I haven't added a transition between JumpDescending and Sliding due to some strange behaviors when jumping across small, but steep, slopes.
To Test, check if the character is sliding in any steep slopes by following the steps in the issue.
Additionally:
- Add a dynamic platform in the environment (with collider and rigidbody) (suggestion: Cube(8))
- Enter Play Mode
- Move the character to step on the platform
- Activate the state machine debug option
- Rotate the platform on the X or Z axis until …

Allow switching from the Idle state to Sliding or JumpDescending

---

UOP1_Project/Assets/Scripts/Input/InputReader.cs

This PR changes input checks inside the InputReader.cs file from the InputActionPhase.Started phase to the Performed phase.
The input system provides the ability to define 'interactions' - different actions which fire off on the same button press depending on the length of the press (Hold, Multi-Tap, etc).
Actions are detected in the Started Phase, and considered complete in the Performed phase.  Currently we only look at the started phase, which will cause issues if we ever want to use the interaction system.
Should not affect any existing functionality, but just conform to best practice (all the official guides show performing callbacks from performed phase, not started phase).
More details here: https://forum.unity.com/threads/controls.980073/#post-6484114

Input checks from Phase.Started => Phase.Performed

---

UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs

When we wanted to click to select spawn location while not in play mode the gizmos was laggy. I added to repaint on mouse move event to always paint the exact location.
[Forum Thread](https://forum.unity.com/threads/spawn-system.980658/)
This PR improves a little bit the **click to set spawn location** feature introduced by @jamercer . Really good work btw, it's a very useful tool.
This change basically makes sure that gizmo cube location is exact at all times while not in play mode.
I just call HandleUtility.Repaint when mouse is moved while we are positioning the spawn location

Repaint when selecting spawn location

---

UOP1_Project/Assets/Scripts/Sound.meta

**[for Bugfix PRs]**  
Issue https://github.com/UnityTechnologies/open-project-1/issues/165
Looks like an extra meta file made it through after our recent Audio System merge. The meta file `Sound.meta` was referencing a folder that no longer exists.

Delete unused metafile for Sound folder

---

UOP1_Project/Assets/Scripts/StateMachine/Editor/UOP1.StateMachine.Editor.asmdef
UOP1_Project/Assets/Scripts/StateMachine/Editor/UOP1.StateMachine.Editor.asmdef.meta

This assembly will mark the editor code for removal when building the project since the Editor folder does not do this automatically inside another assembly.

Added an Editor assembly for the FSM editor scripts

---

UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs
UOP1_Project/Assets/Scripts/Editor/SpawnLocationEditor.cs

Is this PR linked to an issue? If so please link it here, if not please create one first, then link it.
[#157](https://github.com/UnityTechnologies/open-project-1/issues/157) 
Is there a forum thread linked to this issue? If so please link it here. 
No 
How did you resolve this issue?  
I reorganized **ClieckToPlaceHelper** and **SpawnLocationEditor** classes in the way when all editor-dependent functionality were placed in **SpawnLocationEditor** class in Editor folder. 
How can it be verified that the issue has actually been resolved?  
Just try to build project and check there is no compilation errors.

fix: Project won't compile due to a reference to UnityEditor (#157)

---

UOP1_Project/Assets/Scripts/StateMachine/Editor/AddTransitionHelper.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionDisplayHelper.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs.meta
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uss
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uss.meta
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uxml
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uxml.meta

[Generic State Machine](https://forum.unity.com/threads/generic-state-machine.979371/)
This PR adds an Editor Window to edit **TransitionTables**. The purpose of this window is to allow easier accessibility to the multiple transition tables that will take part in the project, and avoid having to scan through the bunch of folders to find the right transition table asset.
The window is accessible through a new menu item:
When opening it up, a list with all the transition tables is displayed (currently only one). You can select any table to draw its inspector inside the same window, and edit it as usual:
This PR also fixes **a lot** of layout issues with `TransitionTableEditor`, and refactors a lot of the code that was using `EditorGUILayout` to use `EditorGUI` instead.

TransitionTableEditorWindow

---

UOP1_Project/Assets/Scripts/Pool/PoolSO.cs

Issue: #242 
Forum thread: https://forum.unity.com/threads/generic-object-pool.990776/#post-6568468
I reset HasBeenPrewarmed to false in the OnDisable method of PoolSO.
To verify:
1. Open the Initialization scene in the project.
2. Press play.
3. Notice the AudioManager has a pool as a child and it has been prewarmed.
4. Exit playmode.
5. Press play.
6. Notice the AudioManager still has a prewarmed pool as a child and no warning is logged about the pool already being prewarmed.

[Object Pool] Fix HasBeenPrewarmed Reset

---

UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs

Reviewing #241 I realized that there was an error in `TransitionTableEditor.cs`. I was null checking `FromState` twice and not checking `ToState`.
This should only happen if a **State** asset is deleted _after_ creating a **Transition** that uses it, so it's very rare and probably why it went undetected.

Hotfix for null checking Transition  Target State.

---

UOP1_Project/Assets/Prefabs/GameplayEssentials/CameraSystem.prefab
UOP1_Project/Assets/Prefabs/GameplayEssentials/SpawnSystem.prefab
UOP1_Project/Assets/ScriptableObjects/EventChannels/FrameObjectEvent_Channel.asset
UOP1_Project/Assets/ScriptableObjects/EventChannels/FrameObjectEvent_Channel.asset.meta
UOP1_Project/Assets/Scripts/CameraManager.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/TransformEventChannelSO.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/TransformEventChannelSO.cs.meta
UOP1_Project/Assets/Scripts/SpawnSystem.cs

Card: https://open.codecks.io/unity-open-project-1/decks/15-code/card/194-decouple-cameramanager-and-spawnsystem
Forum: https://forum.unity.com/threads/decouple-cameramanager-and-spawnsystem-card-194.1016932/
Adapted the changes described on the card: Created Event channel for transform type, `eventChannelSO`, linked all together (`cameraManager`--->`eventChannelSO`<---`spawnSystem`) and raising/receiving the event with transform data.
This way the `cameraManager` should be decoupled out of `spawnSystem`.
----
When removed the old code, I've found there is one more reference to `cameraManager` in `spawnSystem`, when we assign this camera to `Protagonist`:
SpawnSystem.cs
```Csharp
private void SetupCameras(Protagonist player)
{
player.gameplayCamera = _cameraManager.mainCamera.transform; …
```

Decouple CameraManager and SpawnSystem

---

UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLandParticlesActionSO.cs

Addressing this open ticket:
https://open.codecks.io/unity-open-project-1/decks/15-code/card/18k-avoid-spamming-particles-on-sliding
Added a small solution to LandParticle Visuals being spammed when the state machine rapidly switches between the sliding and idle state, which was shown to happen in the ticket above.
After this change, Whenever the PlayLandParticlesAction is exited by the state machine, it checks if total elapsed time is greater then the total elapsed time of the last particle call + a small amount.
If so, only then do we tell the DustParticleController to play, and we also set the new time to beat to be the current time.

Added small internal cooldown to the PlayLandParticlesAction StateAction

---

UOP1_Project/Assets/Scripts/Editor/ScriptableObjectHelper.cs
UOP1_Project/Assets/Scripts/Editor/ScriptableObjectHelper.cs.meta
UOP1_Project/Assets/Scripts/Input/Editor.meta
UOP1_Project/Assets/Scripts/Input/Editor/InputReaderEditor.cs
UOP1_Project/Assets/Scripts/Input/Editor/InputReaderEditor.cs.meta

Added editor for ScriptableObject with events. It allows to automatically show buttons for each event and raise it. Currently it is hooked only on the input SO (so on `InputReaderSO`), but can be attached simply to any other SO and allows user to invoke events from UI where argument are not needed.
I've used reflection to check the SO for event and via backing field they're invoked.
No forum or card link.

Feature/code: Editor for ScriptableObject with events

---

UOP1_Project/Assets/Prefabs/Characters/PigChef.prefab
UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLandParticlesActionSO.cs
UOP1_Project/Assets/Scripts/Effects/DustParticlesController.cs

https://forum.unity.com/threads/puff-of-dust-effects.1002936/#post-6638764
I picked up on this issue through the Codecks card shown below. The forum thread for the puff effects hadn't addressed the card so I got to work on the solution. 
**The Solution**
I made an overload of the existing method `PlayLandParticles` that takes an argument called "intensity". I then rigged the `PlayLandParticlesActionsSO` to call the method with the intensity argument. The intensity is calculated based on how far the player fell during the State it was in. Since that StateAction is only called during the Jump_Decending State, the fall distance is always positive (but I still took the absolute value for safety).
As brought up by @ciro-unity in the [forum …

Control size of landing particles based on fall distance

---

UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Timer_PlantFainting.asset
UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/PlantCritter_TransitionTable.asset

Sometimes when giving the last hit to the plant critter during the plant attack, it happens that the plant is killed without playing the expected BeenHit & Faint animations.
I have just figured out what is going wrong, the attack state in plant critter state machine has transition to dying state, so it happens that the state machine is ahead compare to the animator so some animations are missed. I am removing these transitions (Attack to Dying and Fighting to Dying, and adding BeenHit to Dying).

Corrected plant critter state machine to be aligned with animator

---

UOP1_Project/Assets/Scripts/EditorTools/ClickToPlaceHelper.cs

Hi there, new contributor around here 😄 This is my first contribution so I'm keeping it tiny.
This PR fixes #305 
I resolved it by registering the changes made to the transform with `Undo.RecordObject(transform, $"{gameObject.name} moved by ClickToPlaceHelper");`
It can be verified by following the repro steps in issue #305. Here's a video too:
https://user-images.githubusercontent.com/16073309/104380749-64e6dd80-5523-11eb-8960-73042b23ca5e.mp4

Fixes objects moved by ClickToPlaceHelper not being detected in the scene so cannot be saved

---

UOP1_Project/Assets/Scripts/Inventory/UIInventoryManager.cs

**[for Bugfix PRs]**  
Is this PR linked to an issue? If so please link it here, if not please create one first, then link it. 
> https://github.com/UnityTechnologies/open-project-1/issues/304
How did you resolve this issue?  
> By making sure the item's id is greater then -1 which is what happens after an item is used.
How can it be verified that the issue has actually been resolved?  
> By tring to use an item again.

Fixed ArgumentOutOfRangeexception when trying to use item multiple times

---

UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Localization-Assets-Shared.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Localization-StringTables.asset
UOP1_Project/Assets/Localization Files/Asset Tables/Critters.meta
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters Shared Data.asset
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters Shared Data.asset.meta
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters.asset
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters.asset.meta
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_en.asset
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_en.asset.meta
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_fr.asset
UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_fr.asset.meta
UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab
UOP1_Project/Assets/Prefabs/Props/Collectible Item.prefab
UOP1_Project/Assets/ScriptableObjects/Critters.meta
UOP1_Project/Assets/ScriptableObjects/Critters/PlantCritter.asset
UOP1_Project/Assets/ScriptableObjects/Critters/PlantCritter.asset.meta
UOP1_Project/Assets/Scripts/Characters/Critter.cs
UOP1_Project/Assets/Scripts/Characters/DropItem.cs
UOP1_Project/Assets/Scripts/Characters/DropItem.cs.meta
UOP1_Project/Assets/Scripts/Characters/ScriptableObjects.meta
UOP1_Project/Assets/Scripts/Characters/ScriptableObjects/CritterSO.cs
UOP1_Project/Assets/Scripts/Characters/ScriptableObjects/CritterSO.cs.meta
UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/DestroyCritterSO.cs
UOP1_Project/Assets/Scripts/Inventory/CollectibleItem.cs

Forum thread: [Combat System](https://forum.unity.com/threads/combat-system.1032685/)
The aim of this PR is to add the item dropping to the recently merged combat system. Basically when the plant critter is killed, some collectable items are dropped based on the configuration set up in a new Critter SO attached to the Critter MB script:
This SO will describe a variant of a critter setup (Localized name, Max HP, Max number of items it can drop, the drop rate table associating items to a drop rate (between 0.0 and 1.0)
I took this opportunity to add a Critter Name localization table, I tried to find funny critter names in FR ;) 
Finally in Critter script, the Critter SO is read / used to instantiate the drop result when the critter is killed:
A short demo of this enhancement: …

Added Critter SO - Item drop when killed - FR critter names

---

UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/Attack.anim
UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/Attack.anim.meta
UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/SlimeCritter.controller
UOP1_Project/Assets/Prefabs/Characters/SlimeCritter_Base.prefab
UOP1_Project/Assets/ProBuilder Data.meta
UOP1_Project/Assets/Scripts/Characters/SlimeCritterAttackController.cs
UOP1_Project/Assets/Scripts/Characters/SlimeCritterAttackController.cs.meta

Forum thread: [Slime Critter](https://forum.unity.com/threads/slime-critter.1005712)
Codecks card: [Critters](https://open.codecks.io/unity-open-project-1/decks/65-game-design-wiki/card/14z-critters)
The aim of this PR is to propose an implementation for the propelling effect during the Slime Critter attack.
This animation might be specific to this critter so a new MB script has been created (Slime Critter Attack Controller) which controls the movement of the critter during the attack.
Here is the result in the game:

Slime critter propelling attack movement

---

UOP1_Project/Assets/Scripts/Input/GameInput.cs
UOP1_Project/Assets/Scripts/StateMachine/Core/StateAction.cs
UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateAction.txt
UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateCondition.txt
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/AddTransitionHelper.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/ContentStyle.cs
UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/TransitionDisplayHelper.cs

[Generic State Machine](https://forum.unity.com/threads/generic-state-machine.979371/)
Mainly subtle changes that should make the TransitionTable editor feel better to use.
No changes to the functionality of State Machines, except for moving the call to method `OnStateEnter` of the initial State from the StateMachine's `Awake` to `Start`. This change didn't affect any of the currently implemented State Machines, but it makes more sense and prevents possible bugs down the line. This is because a lot of things get set up during `Awake`. If, say, in `OnStateEnter` we access a field in an **MB** that gets assigned during that **MB**'s `Awake`, but because of execution order the StateMachine's `Awake` gets called before that happens, we would get seemingly random exceptions and undesired …

State Machine Improvements

---

UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/Editor/AnimatorParameterActionSOEditor.cs
UOP1_Project/Assets/Scripts/Editor/CustomBaseEditor.cs
UOP1_Project/Assets/Scripts/Editor/CustomBaseEditor.cs.meta
UOP1_Project/Assets/Scripts/Editor/GameSceneSOEditor.cs

Proposition from Ciro in: https://github.com/UnityTechnologies/open-project-1/pull/258
Create base editor class that contain handy methods to use. 
Make things easier and no more writing repetitive code.
For now, it only contain:
- Draw Non Editable Script Reference()
This PR already implemented to some editor that needed it (no reference to the script):
- GameSceneSO
- AnimatorParameterActionSO
there are actually more:
- TransitionTableEditor
- StateEditor
But for some reason, it can't inherit from the CustomBaseEditor class. Maybe because they are using internal?

Create custom base editor for custom inspector

---

UOP1_Project/Assets/Scripts/Audio/AudioCue.cs
UOP1_Project/Assets/Scripts/Audio/AudioData/AudioCueKey.cs
UOP1_Project/Assets/Scripts/Audio/AudioData/AudioCueKey.cs.meta
UOP1_Project/Assets/Scripts/Audio/AudioManager.cs
UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitter.cs
UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterList.cs
UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterList.cs.meta
UOP1_Project/Assets/Scripts/Characters/ProtagonistAudio.cs
UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayAudioCueActionSO.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/AudioCueEventChannelSO.cs

Forum thread: None
Codecks card: [Audio: Stop vs. FinishAndStop](https://open.codecks.io/unity-open-project-1/decks/15-code/card/19f-audio-stop-vs-finishandstop)
Added the function to control the audio that has been requested to be played
Did some modification in the AudioManager and AudioEventChannel
Noticeable feature:
- You get an AudioCueKey when you request to play audio
- You can use this key to either stop or finish the emitters from the previous request.
- Stop end the audio playback instantly and finish stop the looping
[Video](https://streamable.com/0ozroq)
I chose to use a key to control the emitter to avoid using a emitter that has been put back into the pool. The alternative was to let the user do the pooling. I find the first option cleaner. In any case, can't wait to hear …

Add a Stop and Finish option for the AudioManager

---

UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateConditionSO.cs

[SM Thread](https://forum.unity.com/threads/state-machine.979371/)
Finally, you can now enable the option `Recompile And Continue Playing` without having the PigCheff and every Critter break.
The option was causing more confusion than anything and wasn't being used at all. Every condition had it on since it's the default, so I've left the feature active at all times while removing the toggle as discussed [here](https://forum.unity.com/threads/input-cached-when-not-immediately-consumed-by-a-state.1022698/#post-6786170).

Allowed SM hot reloading and removed "CacheResult" from ConditionSOs

---

UOP1_Project/Assets/Scripts/CameraManager.cs

fix for issue: #340 
link to forum thread: https://forum.unity.com/threads/camera-lerps-into-place-at-the-beginning-of-a-scene.1052282/
**How did you resolve this issue?** 
After a new scene is loaded, the Camera Manager in the scene manager calls SetupProtagonistVirtualCamera() to set the target of the free look vcam. After setting the target, I have used OnTargetWarped() to warp the camera close the the player without lerping. I have also added a field in camera manager called _SpawnDistanceFromPlayer to set how far from the player the camera will warp. I found the most consistent results in terms of camera movement for a value of zero.
**How can it be verified that the issue has actually been resolved?**  
you may follow the steps to reproduce the bug mentioned in the issue, the vcam …

fix for camera Lerps into place

---

UOP1_Project/Assets/Scenes/PersistentManagers.unity
UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeChannelSO.asset
UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeChannelSO.asset.meta
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/BoolEventChannelSO.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/UI/FadeChannelSO.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/UI/FadeChannelSO.cs.meta
UOP1_Project/Assets/Scripts/UI/FadeManager.cs
UOP1_Project/Assets/Scripts/UI/FadeManager.cs.meta

This implements the UI fader to black card using events and scriptable objects. To use, add a FadeChannelSO to the relevant script, assign the scriptable object, the call either Fade, FadeIn, or FadeOut. Has parameters for duration and target color. This is usable anywhere and at any time, but contains no safeguards besides preventing multiple fades from happening at the same time.
Note: This modifies the PersistentManagers scene and adds an Image UI element that it depends on.
Forum Thread: [https://forum.unity.com/threads/ui-fader-to-black.1038013/](https://forum.unity.com/threads/ui-fader-to-black.1038013/)
I would like to thank forum user [Swerik ](https://forum.unity.com/members/swerik.5425601/)for proposing the implementation plan I ended up using.

UI Fade in and out code and implementation

---

UOP1_Project/Assets/Scripts/Audio/AudioManager.cs

The `UnregisterChannel` method was not unsubscribing from the delegates properly.
Not sure if this is the right procedure for a small bugfix like this; I didn't think it was worth creating an issue for this

AudioManager UnregisterChannel fix

---

UOP1_Project/Assets/Scripts/Localization/LocalizeComponent_TMProFont.cs
UOP1_Project/Assets/Scripts/Localization/LocalizeComponent_TMProFont.cs.meta
UOP1_Project/Assets/Scripts/Localization/LocalizeTMProFontEvent.cs
UOP1_Project/Assets/Scripts/Localization/LocalizeTMProFontEvent.cs.meta

**Forum:**
[Link to forum](https://forum.unity.com/threads/localization-system.982776/#post-6631024)
**Purpose:**
Localize font base on the game language.
Characters from other languages might be missing if the font doesn't change. (Mainly Asian languages like Chinese, Korean, Japanese..)
**Changes:**
(Add 2 short scripts to implement font localization.)
1. LocalizeTMProFontEvent.cs - Component to localize a TMP_FontAsset
2. LocalizeComponent_TMProFont.cs - TextmeshProUGUI context menu "Localize String And Font"
**Note**
By default, if we create our Font Asset Table with the name "Fonts" and key "font", the component will be automatically set up. Or we can always re-define this name string in the code easily. 
The naming convention of the classes followed the names and scripts from the …

Add feature to localization : Localize TMP font

---

UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-AssetTables_BundledAssetGroupSchema.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-Shared_BundledAssetGroupSchema.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-en_BundledAssetGroupSchema.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-fr_BundledAssetGroupSchema.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Locales_BundledAssetGroupSchema.asset
UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-StringTables_BundledAssetGroupSchema.asset

Fixes #385. This is a known bug in Addressables. The fix is to ensure that the Addressable groups are using Append+Hash naming scheme.
More details can be found here, specifically step 4: https://forum.unity.com/threads/troubleshooting-addressables-issues.1060346/
This PR will fix the locales so they work correctly in builds.
n.b. I'm informed a fix for this will be coming in the Addressables package at a later date.

Fixes #385 where no locale is selected in a build

---

UOP1_Project/Assets/Scripts/SceneManagement/InitializationLoader.cs

Question:
I recently learned about open projects from dev blog 4 because of the addressables system (as i'm looking to implement a similar loading strategy) and i'm digging through the Initialization code and i'm wondering why the Async Operation Handle Result is not used?  Here is a PR that switches to using the Async Operation Handle Result - is this the more correct paradigm?

I'm curious why the AO handle result is not used in this context?

---

UOP1_Project/Assets/Scenes/WIP/TestingGround.unity
UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/Conditions/IsDialogueActiveCondition.asset
UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/Conditions/IsDialogueActiveCondition.asset.meta
UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/SlimeRockCritter/SlimeRockCritter_TransitionTable.asset
UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsDialogueActiveConditionSO.cs
UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsDialogueActiveConditionSO.cs.meta

Issue:https://github.com/UnityTechnologies/open-project-1/issues/418
Forum: https://forum.unity.com/threads/bug-enemy-attacks-protagonist-during-a-dialogue.1103305/
This PR has two main changes:
1. Introduce `IsDialogueActive` Condition
2. Updates `Slime Critter` state machine to include aforementioned Condition in transition from `Idle` or `Roaming` state to `Alert` state
`IsDialogueActive`Condtion simply listens to Start and End dialog events emitted by Dialogue Manager. It preserves internal boolean value that becomes truthful when the new dialogue starts, falsy when dialogue ends. Assuming we may have only one active dialogue at a time, Condition should correctly indicate if there is any dialogue active currently. Finally,` Condition` uses that internal value as a result of …

[Bugfix] New condition prevents Critter from attacking when dialogue on

---

UOP1_Project/Assets/Shaders/Clouds.shadergraph
UOP1_Project/Assets/Shaders/CustomHLSL/CustomLighting.hlsl
UOP1_Project/Assets/Shaders/Toon.shadergraph
UOP1_Project/Assets/Shaders/Toon_DetailMaskTint.shadergraph
UOP1_Project/Assets/Shaders/Toon_Dissolve.shadergraph
UOP1_Project/Assets/Shaders/Toon_DoubleSided.shadergraph
UOP1_Project/Assets/Shaders/Toon_Ground.shadergraph
UOP1_Project/Assets/Shaders/Toon_RandomPositionTint.shadergraph
UOP1_Project/Assets/Shaders/Toon_Rocks.shadergraph
UOP1_Project/Assets/Shaders/Toon_Slime.shadergraph
UOP1_Project/Assets/Shaders/Toon_Wind.shadergraph
UOP1_Project/Assets/Shaders/Unused/Toon_WithOutline.shadergraph

This PR simplifies the ShaderGraph shaders: the multi_compile pragma can be in an include file, the keywords don't need to be declared separately on each Shader Graph. This is error prone, since someone could accidentally remove a keyword or use it in the graph incorrectly. Also, changing keywords (e.g. finding another one needs to be added to support lighting mode XY) is way harder if you have to hunt the keywords down in 10+ shaders.
The list of multi_compiles comes from URP's Lit.shader and contains a couple more items than were in ShaderGraph previously. I'm not sure if all lighting modes are used in Chop Chop but I think a more "complete" toon lighting can't hurt to have.

Add multi_compile keywords to CustomLighting.hlsl, remove ShaderGraph keywords

---

UOP1_Project/Assets/Scripts/UI/UIPaginationFiller.cs

Moved the code that instantiates the _instantiatedImages to the SetPagination method.
Fixes #440  
Issue link: https://github.com/UnityTechnologies/open-project-1/issues/440
Forum thread: https://forum.unity.com/threads/settings-menu-not-properly-populated.1115938/
Fixed by moving the instantiation of the list of images to the SetPagination method. Since the instantiation only happens once, this should be ok.
To confirm the issue is resolved, open the Settings menu and confirm that the different options are displayed, and that no NullReferenceException is thrown.

Fixed Settings menu not properly populating

---

UOP1_Project/Assets/Prefabs/Gameplay/CameraSystem.prefab
UOP1_Project/Assets/ScriptableObjects/Events/Camera.meta
UOP1_Project/Assets/ScriptableObjects/Events/Camera/CameraShakeEvent.asset
UOP1_Project/Assets/ScriptableObjects/Events/Camera/CameraShakeEvent.asset.meta
UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/PlantCritter/States/GettingHit.asset
UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/SlimeRockCritter/States/GettingHit.asset
UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ShakeCamAction.asset
UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ShakeCamAction.asset.meta
UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/States/GettingHit.asset
UOP1_Project/Assets/Scripts/Camera/CameraManager.cs
UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ShakeCamActionSO.cs
UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ShakeCamActionSO.cs.meta

Feature described in this card:
https://open.codecks.io/unity-open-project-1/decks/15-code/card/1gk-camera-shake-on-hit
Added Action to GettingHit state, created Void Event Channel and raising it in OnStateEnter() of Action.
Created GO under CameraSystem with Impulse Source. Added reference to Impulse Source and Event SO to Camera Manager script and subscribed.

Add camera shake on protagonist hit.

---

UOP1_Project/Assets/Scripts/Audio/AudioCue.cs

Issue: https://github.com/UnityTechnologies/open-project-1/issues/453
Codecks: https://open.codecks.io/unity-open-project-1/decks/13-bugs/card/1go-looping-sfx-are-still-playing-when-changing-scene
Forum: https://forum.unity.com/threads/suggestions-on-where-to-start.1127687/#post-7279576
Added a call to StopAudioCue() to the AudioCue script's OnDisable method.
To verify:
1. Start the Beach scene.
2. In the hierarchy explorer, go to PersistentManagers > AudioManager > SoundEmitterPool and note that one of its children is continuously playing the Env_Campfire audio clip.
3. Exit to Field_Hill. The campfire is no longer audible. The associated SoundEmitter may still be in the pool but is now disabled.
4. Return to the Beach. There is once again a SoundEmitter looping the campfire audio. …

Stop audio cue when associated Component is destroyed

---

UOP1_Project/Assets/Scenes/Managers/PersistentManagers.unity
UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeCompleteEvent.asset
UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeCompleteEvent.asset.meta
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/LoadEventChannelSO.cs
UOP1_Project/Assets/Scripts/Events/ScriptableObjects/UI/FadeChannelSO.cs
UOP1_Project/Assets/Scripts/SaveSystem/SaveSystem.cs
UOP1_Project/Assets/Scripts/SceneManagement/LocationExit.cs
UOP1_Project/Assets/Scripts/SceneManagement/SceneLoader.cs
UOP1_Project/Assets/Scripts/UI/FadeManager.cs

[Forum Thread](https://forum.unity.com/threads/ui-fader-to-black.1038013/)
This PR links Fade Manager with SceneLoader to enable screen fading during scene loads. Screen is fading when entering different locations, when we are not showing loading screen.
The communication is based on Channel Events.

Delay loading to accommodate the duration of fade out

---

UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLandParticlesActionSO.cs

Issue:
https://open.codecks.io/unity-open-project-1/decks/13-bugs/card/1h2-landing-particles-and-sfx-play-when-attacking-in-the-air
Thread:
https://github.com/UnityTechnologies/open-project-1/issues/459
Like mentioned in the thread, the bug is caused because the state machine goes Ascending->Descending->DescendingAttacking where Descending calls the particles when exiting. I fixed this simply by adding a ground check on the PlayLandParticles action, so it cannot play in the air. The issue can be verified by playing the game, jumping and then attacking.

Fixed landing particles playing in air when attacking bug

---

UOP1_Project/Assets/Prefabs/Gameplay/EditorInitializer.prefab
UOP1_Project/Assets/Scripts/SceneManagement/EditorColdStartup.cs
UOP1_Project/Assets/Scripts/SceneManagement/SceneLoader.cs

I think it makes sense to create the save file on editor cold startup, since we have developers who may play the game without going through the initialization scene.
I first noticed this when trying to enter play mode on the beach scene for the second time. I had no save file present, which caused the beach scene to not fully load and display a "no cameras rendering" message. 
As for how play mode works the first time.... I believe this is due to the async scene loading that we are doing with `EditorColdStartup`. 
The first time you hit play mode, you will observe that the `EditorColdStartup` will call `loadEventChannelSO.RaiseEvent` before the save system has had a chance to subscribe to `_loadLocation.OnLoadingRequested`. Because the save system is not subscribed, we haven't done any …

Create save file on editor cold startup if it is not present (allow users to use play mode more than once)

---

UOP1_Project/Assets/Scripts/SaveSystem/FileManager.cs

Issue Link: https://github.com/UnityTechnologies/open-project-1/issues/399
Forum Link: https://forum.unity.com/threads/save-system.1056311/#post-6983891
Solution:
I check if the saved file exists.
* With this current solution, the game doesn't create anymore the save.chop file when the player runs a scene different from the **Initialization** scene
Steps to check if it's ok:
- Remove all save files in the persistence folder (or change temporary the name)
- Open and run the Beach scene
- the game will wok and the save file will not be created

fix: checking if the old save file exists
