- UOP1_Project/Assets/Scripts/Characters/Character.cs
Bug is fixed.
Issue: https://github.com/UnityTechnologies/open-project-1/issues/7
Card: https://unity-open-projects.codecks.io/decks/13/card/16e-movement-is-very-snappy-if-using-keyboard
> Fixed snappy movement bug

- UOP1_Project/Assets/Scripts/Characters/Character.cs
#38 
Replaced the condition with one that works more consistently.
> Fixed an issue regarding player jump not getting canceled in a few cases

- UOP1_Project/Assets/Scripts/CameraManager.cs
- UOP1_Project/Assets/Scripts/Characters/Character.cs
- UOP1_Project/Assets/Scripts/InputReader.cs
- UOP1_Project/Assets/Scripts/SpawnSystem.cs
Removing unused `using` directives.
> Removed unused imports

- UOP1_Project/Assets/Scripts/InputReader.cs
Forum thread: https://forum.unity.com/threads/controls.980073/#post-6455884
Without event keyword anyone can call such delegates
> Fixing events not being events

- UOP1_Project/.gitignore
For [Rider IDE](https://www.jetbrains.com/rider/) users.
> feat(gitignore): Add `.idea/` cache directory

- UOP1_Project/Assets/Prefabs/GameplayEssentials/CameraSystem.prefab
- UOP1_Project/Assets/Scripts/CameraManager.cs
- UOP1_Project/Assets/Scripts/Input/GameInput.cs
- UOP1_Project/Assets/Scripts/Input/InputReader.cs
- UOP1_Project/Assets/Settings/Input/GameInput.inputactions
Do you have a forum thread linked to this PR? 
https://forum.unity.com/threads/controls.980073/#post-6490833
What will this PR bring to the project for everyone?  
camera can be controlled by mouse- hold down right button and move mouse around.
Why are these changes necessary?  
it's good quality of life for mouse + keyboard folks =)
How did you implement them?  
Used the new input system.  added a binding for camera movement to mouse delta.  added a new action on RMB to enable/disable mouse control of camera system.
> Simple mouse based camera controls

- UOP1_Project/Assets/Scripts/StateMachine/Core/StateTransition.cs
- UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs
This is a fix for #148 
[Here is a post](https://forum.unity.com/threads/generic-state-machine.979371/page-5#post-6494674) explaining why it was happening and the solution.
> Fix Error when initializing StateMachine

- UOP1_Project/Assets/ScriptableObjects/Protagonist/CharacterTransitionTable.asset
- UOP1_Project/Assets/ScriptableObjects/Protagonist/States/Idle.asset
- UOP1_Project/Assets/ScriptableObjects/Protagonist/States/Sliding.asset
Solves [#187](https://github.com/UnityTechnologies/open-project-1/issues/187).
I followed @DeivSky's [suggestion](https://github.com/UnityTechnologies/open-project-1/issues/187#issuecomment-728195345) and just added a new transition from Sliding to JumpDescending state when the character is not grounded while
in Sliding state.
> Added Sliding to JumpDescending protagonist transition

- UOP1_Project/Assets/Prefabs/Props/Pottery.prefab
This PR solves #193. See the discussion there for more details.
Before:
After:
> Changed Pottery game object collider to box

- UOP1_Project/Assets/Scripts/Audio/AudioManager.cs
- UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterPoolSO.cs
- UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs
- UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs
- UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs
- UOP1_Project/Assets/Scripts/Pool/IPool.cs
- UOP1_Project/Assets/Scripts/Pool/PoolSO.cs
Forum: https://forum.unity.com/threads/generic-object-pool.990776/#post-6541984
Added Prewarm to IPool
Implemented Prewarm in PoolSO
Removed private InitializePool in ComponentPoolSO
Added Lazy-Loaded PoolRootObject to ComponentPoolSO
Removed InitialPoolSize property from ComponentPoolSO
Modified Examples to use new workflow
Modified Audio scripts to use new workflow
> Add Explicit Prewarm to Pool

- UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
The handler method for `listView.onSelectionChanged` assignes every time the window got focus. The event triggers multiple times, so we need to clean it up on refresh.
> Editor window multiple event trigger fix

- .gitignore
- UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Conditions/IsActuallyMoving.asset
- UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Conditions/IsActuallyMoving.asset.meta
- UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/PigChef_TransitionTable.asset
- UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsActuallyMovingConditionSO.cs
- UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsActuallyMovingConditionSO.cs.meta
- UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsSlidingConditionSO.cs
Added Sliding to JumpAscending because player was unable to jump if sliding which caused the player to get stuck in geometry/holes.
https://drive.google.com/file/d/17W4yQk7EHbmIGfpJtbvGedsDUlmHogpp/view?usp=sharing
Issue: #228
> State Machine - Proposed fix for Issue 228

- UOP1_Project/Assets/Scripts/Editor/ReplaceTool.cs
> ReplaceTool selection and sibling index fix

- UOP1_Project/Assets/Art/Accessories/EarCurls/earCurls.mat
- UOP1_Project/Assets/Art/Accessories/Moustache/moustache.mat
- UOP1_Project/Assets/Scenes/Skybox/ClearSky.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/2. Glade - Forest 1.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/4. Forest Maze.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/5. Rocky Path.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/CloudRotation.cs
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/CloudRotation.cs.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Cloud.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Cloud.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Descriptions.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Descriptions.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Forest.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Forest.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Glade.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Glade.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Mountain.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Mountain.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Placeholders.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Placeholders.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Down.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Down.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Up.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Up.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Water.mat
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Water.mat.meta
- UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Proposal 1.unity.meta
Added a General Map folder that contains the General Map whiteboxing scene.
> General Map Whiteboxing_1

- UOP1_Project/Assets/Scripts/SaveSystem.meta
- UOP1_Project/Assets/Scripts/SaveSystem/Save.cs
- UOP1_Project/Assets/Scripts/SaveSystem/Save.cs.meta
- UOP1_Project/Assets/Scripts/SaveSystem/SaveSystem.cs
- UOP1_Project/Assets/Scripts/SaveSystem/SaveSystem.cs.meta
- UOP1_Project/Assets/Scripts/SaveSystem/TestScript.meta
- UOP1_Project/Assets/Scripts/SaveSystem/TestScript/TestScript.cs
- UOP1_Project/Assets/Scripts/SaveSystem/TestScript/TestScript.cs.meta
A saving/loading system is necessary and is a core part of the game.
This pull request comprises of an manageable way to serialize the necessary data that needs to persist between game session.
In short, a save/load system.
The explanation for how to use the system, can be found inside a script called `TestScript.cs`.
Official thread on forums:-
[Progress Saving System](https://forum.unity.com/threads/progress-saving-system.980313/)
> Added Modular Save System functionality

- UOP1_Project/Assets/Scripts/Editor/SOsQuickAccessToolWindow.cs
- UOP1_Project/Assets/Scripts/Editor/SOsQuickAccessToolWindow.cs.meta
Do you have a forum thread linked to this PR?  
https://forum.unity.com/threads/editor-window-to-efficiently-productively-find-scriptable-objects-sos.1030345/
What will this PR bring to the project for everyone?  
Efficiency and more productivity.
Why are these changes necessary?  
Because I have not contributed to this project yet and I want to.
How did you implement them?  
Details in Forum Link.
> Editor Window to efficiently find SOs

- UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Inventory.cs
- UOP1_Project/Assets/Scripts/Inventory/UIInventoryManager.cs
- Added expected letter 'n' to IngredientsAvailability function in **Inventory.cs**. (Was originally IngredietsAvailability).
- Also updated the IngredientsAvailability function call in **UIInventoryManager.cs** to reflect this spelling change.
Issue: N/A
Card: N/A
> Corrected Small Typo in Function Declaration

- UOP1_Project/Assets/Scripts/SceneManagement/LoadingScreenManager.cs
In LoadingScreenManager.cs we subscribed to a listener (+=) in OnDisable instead of unsubscribing (-=).
Issue N/A
Card N/A
> Fixed a simple typo in LoadingScreenManager

- UOP1_Project/Assets/Prefabs/Gameplay/MusicPlayer.prefab
- UOP1_Project/Assets/Prefabs/UI/GameplayScene/Pause_Screen.prefab
- UOP1_Project/Assets/ScriptableObjects/UI/OnPauseOpened.asset
- UOP1_Project/Assets/ScriptableObjects/UI/OnPauseOpened.asset.meta
- UOP1_Project/Assets/Scripts/Audio/MusicPlayer.cs
- UOP1_Project/Assets/Scripts/UI/UIPause.cs
Feature described in this card:
https://open.codecks.io/unity-open-project-1/decks/15-code/card/1gx-implement-pause-menu-music
Implemented using events, added required SOs to Music Player prefab.
To test simply open and close pause menu (ESC key)
> Implement pause menu music

- UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/SlimeRockCritter/Actions/ChasingTargetAction.asset
- UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ChasingTargetActionSO.cs
Forum link: https://forum.unity.com/threads/enemy-attacks-protagonist-during-a-dialogue.1103305/
This PR sets Game State to combat when SlimeCritter detects protagonist and reverts to prev state when it loses the protagonist
> [Feature] Set Game to Combat when Critter detects player

- UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ChangeGameStateActionSO.cs
Just another little PR. Looks like the summary of this SO was copypasta'd from [the aerial movement SO](https://github.com/UnityTechnologies/open-project-1/blob/51e485e735bb61078d70c86c8fad7dd2a3c853bf/UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/AerialMovementActionSO.cs) ✌️
> Update summary of ChangeGameStateActionSO.cs

- UOP1_Project/Assets/Scripts/SceneManagement/SceneLoader.cs
There's no forum thread/post associated with this change – it just fixes a _very_ minor typo in the source.
Thanks for reviewing!
> Fix typo in SceneLoader.cs
